// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: protos/swagger.proto

package swagger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SwaggerServiceClient is the client API for SwaggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwaggerServiceClient interface {
	CreateSwagger(ctx context.Context, in *Swagger, opts ...grpc.CallOption) (*Response, error)
}

type swaggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwaggerServiceClient(cc grpc.ClientConnInterface) SwaggerServiceClient {
	return &swaggerServiceClient{cc}
}

func (c *swaggerServiceClient) CreateSwagger(ctx context.Context, in *Swagger, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/SwaggerService/createSwagger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwaggerServiceServer is the server API for SwaggerService service.
// All implementations must embed UnimplementedSwaggerServiceServer
// for forward compatibility
type SwaggerServiceServer interface {
	CreateSwagger(context.Context, *Swagger) (*Response, error)
	mustEmbedUnimplementedSwaggerServiceServer()
}

// UnimplementedSwaggerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSwaggerServiceServer struct {
}

func (UnimplementedSwaggerServiceServer) CreateSwagger(context.Context, *Swagger) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSwagger not implemented")
}
func (UnimplementedSwaggerServiceServer) mustEmbedUnimplementedSwaggerServiceServer() {}

// UnsafeSwaggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwaggerServiceServer will
// result in compilation errors.
type UnsafeSwaggerServiceServer interface {
	mustEmbedUnimplementedSwaggerServiceServer()
}

func RegisterSwaggerServiceServer(s grpc.ServiceRegistrar, srv SwaggerServiceServer) {
	s.RegisterService(&SwaggerService_ServiceDesc, srv)
}

func _SwaggerService_CreateSwagger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Swagger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwaggerServiceServer).CreateSwagger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SwaggerService/createSwagger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwaggerServiceServer).CreateSwagger(ctx, req.(*Swagger))
	}
	return interceptor(ctx, in, info, handler)
}

// SwaggerService_ServiceDesc is the grpc.ServiceDesc for SwaggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwaggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SwaggerService",
	HandlerType: (*SwaggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createSwagger",
			Handler:    _SwaggerService_CreateSwagger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/swagger.proto",
}
